// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_2sbvcY4RtyrQQXKf_h26_xDy8UAH-w',
    appId: '1:959626589629:web:06877ffeeba3ad5c91ced4',
    messagingSenderId: '959626589629',
    projectId: 'fkids-290',
    authDomain: 'fkids-290.firebaseapp.com',
    storageBucket: 'fkids-290.appspot.com',
    measurementId: 'G-39FBT3R6XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7khTLuTIJhUJgSLRsXdT8Tc4FRZGuAs',
    appId: '1:959626589629:android:cc6dfffad46e415591ced4',
    messagingSenderId: '959626589629',
    projectId: 'fkids-290',
    storageBucket: 'fkids-290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_5b6Iq_FcYPQ-FgE-6YX0ba_cgfSO9Q',
    appId: '1:959626589629:ios:7d30e4005e272d9391ced4',
    messagingSenderId: '959626589629',
    projectId: 'fkids-290',
    storageBucket: 'fkids-290.appspot.com',
    iosClientId: '959626589629-jj0oop9nuqe6ic7afrksdh8rq9amli52.apps.googleusercontent.com',
    iosBundleId: 'vn.edu.futurelang.futurekids',
  );
}
